#version 460

layout(binding=1)
uniform Uniform {
    int x;
    int y;
    int z;
} u;

void main() {
    int _0 = 1 / u.x;
    int _1 = u.x / u.x;
    int _2 = 2 * u.x / 2;
    int _3 = (4 * u.x + 2 * u.y) / 2;
    int _4 = (4 * u.x + 2 * u.y) / 3;
    int _5 = (4 * u.x + 2 * u.y) / 3 / 5;
    int _6 = (4 * u.x + 2 * u.y) / 3 / 2;
    int _7 = ((4 * u.x + 2 * u.y) / 3) * u.z / 2;
    int _8 = ((4 * u.x + 2 * u.y) / 2) * u.z / 2;
}
